apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8test-deployment
  labels:
    app: k8test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8test
  template:
    metadata:
      labels:
        app: k8test
    spec:
      containers:
        - name: nodeserver
          image: puthaplnrao/k8test:latest
          ports:
            - containerPort: 3000
